---
# tasks file for homedir-shell
- name: Print message
  debug:
    msg: shell config {{ shell }}

- name: .profile base
  copy:
    src: profile.sh
    dest: $HOME/.profile

- name: Install zsh
  package:
    name: zsh
    state: present
  become: yes
