---
# tasks file for homedir-shell
- name: Set {{ shell }} as default shell
  command:
    cmd: chsh
    argv:
      shell:
        - --shell
        - $(which {{ shell }})
        - $USER
  become: yes
